import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="coder, hunting coder, blog" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <img className={styles.myImg} src="homeimg.jpg" alt="coder image" />
        <h1>
          <span className={styles.title}>&lt;Hunting Coder/&gt;</span>
        </h1>
        <div className={styles.container}>
          <h2 className={`${styles.verticalMar2} ${styles.h1}`}>Letest Blogs</h2>
          <div>
            <Link className={styles.underline} href="/blogpost/python-learn">
              <h2 className={`${styles.verticalMar} ${styles.h2}`}>
                What is JavaScript in 2023
              </h2>
            </Link>
            <p>JavaScript is the language used to design logic for the web Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur repellat unde similique explicabo perspiciatis soluta, quis sapiente obcaecati nobis laudantium minima id. lorem333</p>
            <button type="submit" className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={`${styles.verticalMar} ${styles.h2}`}>
              What is JavaScript in 2023
            </h3>
            <p>JavaScript is the language used to design logic for the web</p>
            <button type="submit" className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={`${styles.verticalMar} ${styles.h2}`}>
              What is JavaScript in 2023
            </h3>
            <p>JavaScript is the language used to design logic for the web</p>
            <button type="submit" className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </div>
  );
}
